server:
  port: ${SERVER_PORT}

spring:
  application:
    name: skill-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

# Set spring to only create beans when needed
  main:
    lazy-initialization: true

# Register to service discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL}

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
